# Generated by Django 2.2.7 on 2019-11-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='body',
            field=models.TextField(),
        ),
    ]
