# Generated by Django 2.2.7 on 2019-11-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191122_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Blog',
        ),
    ]
